image: gcc
stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update --yes
  - apt-get upgrade --yes
  - apt-get install cmake python3-dev doxygen graphviz gcovr llvm --yes

Build-Library:
  stage: build
  tags:
    - dcp-aitf
    - linux
  script:
    - echo Building SpiderMonkey
    - curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -s -- -y #install rust compiler
    - wget -q https://ftp.mozilla.org/pub/firefox/releases/102.2.0esr/source/firefox-102.2.0esr.source.tar.xz
    - tar xf firefox-102.2.0esr.source.tar.xz
    - cd firefox-102.2.0/js/src
    - sed -i 's/bool Unbox/JS_PUBLIC_API bool Unbox/g' ./public/Class.h           # need to manually add JS_PUBLIC_API to js::Unbox until it gets fixed in Spidermonkey
    - sed -i 's/bool js::Unbox/JS_PUBLIC_API bool js::Unbox/g' ./vm/JSObject.cpp  # same here
    - cp ./configure.in ./configure
    - chmod +x ./configure
    - mkdir _build
    - cd _build
    - ../configure --disable-jemalloc --with-system-zlib --with-intl-api --enable-optimize
    - make
    - make install
    - cd ../../../..
    - echo Building the library
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - echo Build complete
  cache:
    key: build
    paths:
     - build/*
     - firefox-102.2.0/*

Run-GoogleTests:
  stage: test
  script:
    - cd firefox-102.2.0/js/src/_build
    - make install
    - cd ../../../..
    - cd build
    - make && make tests
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml
    - cd tests && ctest
    - cd ../src
    - python -m pytest ../../tests/python
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml
  cache:
    key: build
  tags:
    - dcp-aitf
    - linux

pages:
  stage: deploy
  dependencies:
    - Build-Library
  script: 
    - mkdir .public
    - cp -r ./build/docs/doc_doxygen/html/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
  cache:
    key: build
  tags:
    - dcp-aitf
    - linux

