[tool.poetry]
name = "pythonmonkey"
version = "0.1.0"
description = ""
authors = ["Caleb Aikens <caleb@distributive.network>", "Tom Tang <xmader@distributive.network>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires        = ['setuptools>=61.0']                  # 'cython'
build-backend   = 'setuptools.build_meta'


