[tool.poetry]
name = "pythonmonkey"
version = "0.1.0"
description = ""
authors = ["Caleb Aikens <caleb@distributive.network>", "Tom Tang <xmader@distributive.network>"]
readme = "README.md"
packages = [
  { include = "pythonmonkey", from = "python" },
]
include = [
  "python/pythonmonkey/pythonmonkey.so",
  "python/pythonmonkey/libmozjs*",

  "python/pythonmonkey/node_modules/**/*",

  # include all files for source distribution
  { path = "src", format = "sdist" },
  { path = "include", format = "sdist" },
  { path = "cmake", format = "sdist" },
  { path = "docs", format = "sdist" }, # TODO: organize files
  { path = "externals", format = "sdist" },
  { path = "format", format = "sdist" },
  { path = "tests", format = "sdist" },
  { path = "CMakeLists.txt", format = "sdist" },
  { path = "*.sh", format = "sdist" },
  { path = "version.txt", format = "sdist" }, # FIXME: Do we really need this?
]


[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.build]
script = "build.py"
generate-setup-file = false 


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pip = "^23.1.2"
numpy = [
  # numpy hasn't packaged for Python 3.12 yet
  # TODO: remove this once numpy releases for Python 3.12
  {url = "https://people.distributive.network/xmader/numpy-1.24.3-cp312-cp312-linux_x86_64.whl", python = "3.12.*", platform = "linux"},
  {url = "https://people.distributive.network/xmader/numpy-1.24.3-cp312-cp312-macosx_10_9_x86_64.whl", python = "3.12.*", platform = "darwin"},
  {version = "^1.24.3", python = "<3.12"},
]

[build-system]
requires = ["poetry-core>=1.0.0a9"]
build-backend = "poetry.core.masonry.api"

