name: patch

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version of `pythonmonkey` to patch
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Patch pythonmonkey ${{ github.event.inputs.version }}
        run: |
          pip install --disable-pip-version-check uv
          uv run patch.py ${{ github.event.inputs.version }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    needs: build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Publish to PyPI
        run: |
          pip install --disable-pip-version-check uv
          uv publish --verbose
