name: 'Build and publish package'

on:
  push:
    tags:
      - '*'

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  deploy:
    needs: [tests]
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ] # , 'windows-latest', 'macos-latest' ]
        python_version: [ '3.9', '3.10', '3.11' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: "poetry"
          update-environment: true
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Setup cmake
        run: |
          sudo apt-get install -y cmake doxygen graphviz gcovr llvm
          poetry install --no-root
      - name: Cache spidermonkey build
        id: cache-spidermonkey
        uses: actions/cache@v3
        with:
          path: |
            ./build/*
            ./firefox-102.2.0/*
            ./_spidermonkey_install/*
          key: ${{ runner.os }}-spidermonkey
      - name: Build-Library
        if: ${{ steps.cache-spidermonkey.outputs.cache-hit != 'true' }}
        run: ./setup.sh
      - name: Buid and Publish package
        run: |
          poetry build
          ls -lah ./dist/
          #poetry publish --no-interaction --build --username __token__ --password $PYPI_API_TOKEN
